---
editor: 
  markdown: 
    wrap: sentence
---

# Discusión y conclusiones

Los resultados presentados nos llevan a las siguientes conclusiones en relación con las hipótesis planteadas: 

En primer lugar, respecto a la hipótesis 1 - “La pandemia ha aumentado el empleo informal”: resultaría intuitivo responder que sí es el caso. Efectivamente, se ha podido observar que el empleo informal ha aumentado entre 2019 y 2021 en un 5%; sin embargo, esta hipótesis se podría aceptar de manera parcial; ya que, en términos absolutos, en el año 2020 (inicio de la pandemia) se perdieron alrededor de un millón doscientos empleos informales y 900 mil empleos formales. Esta pérdida de empleo fue más pronunciada en Lima Metropolitana y la Costa Norte. No obstante, en 2021, hubo una recuperación del empleo informal que superó el nivel prepandemia lo cual no fue el caso del empleo formal. Por lo que podemos concluir que durante la pandemia tanto el empleo formal como informal se vieron reducidos, mas el empleo informal pudo recuperarse hacia 2021.

En segundo lugar, la hipótesis 2 corresponde a la afirmación sobre si el incremento del empleo informal se dio principalmente en zonas y grupos vulnerables, especialmente: A) zonas urbanas de la Sierra y Selva, B) ciudades de pequeña y mediana escala, C) entre jóvenes y mujeres, D) entre los trabajadores con menor nivel educativo. 

Considerando que nos referimos a un aumento del empleo informal en términos relativos, hemos podido observar que: 

A) Efectivamente ha aumentado la informalidad especialmente en la Selva Alta, Sierra Centro y la Costa Sur. En cambio, fue menor el aumento de empleo informal en lugares como Lima Metropolitana y la Costa Norte; sin embargo, en estas zonas destacó la pérdida de empleo en general.

B) Hacia el 2021, sobre todo las ciudades medianas de entre 50 mil y 500 mil habitantes no solo tuvieron una amplia pérdida de empleo, sino que también se constata un aumento de la informalidad. En el caso de los trabajadores con empleo formal, estos vieron su sueldo reducido en mayor proporción que los trabajadores informales salvo en las ciudades pequeñas y medianas. En cambio, en la ciudades grandes la protección de los salarios formales fue mucho menor.

C) Se observó que 7 de cada 10 mujeres que eran jefas de hogar se encontraban en la informalidad, demostrando que hay una predominancia de hogares conducidos por mujeres que se encuentran en la informalidad. No obstante, se evidenció un mayor aumento de hombres jefes de hogar durante la pandemia con alrededor de 5% entre 2019 y 2021. Durante la pandemia, se observa que 1 de cada 7 hombres trabajadores perdieron su empleo, mientras que 1 de cada 5 mujeres perdieron su empleo. Si bien hacia 2021, se muestra una recuperación tanto en hombres como mujeres; no obstante, es más lenta en el caso de las trabajadoras. Asimismo, se pudo corroborar que en primera instancia fueron los jefes de hogar entre 60 y 64 años quienes fueron los más afectados, seguido de los adultos jóvenes entre 25 y 44 años lo que se alinea con la hipótesis de @higa2021. Cabe mencionar que, en la pandemia se muestra un aumento de los trabajadores familiares no remunerados, lo cual podría ser un indicador de la recomposición en las labores del hogar optando por emplear trabajadores familiares sin paga alguna para sortear los impactos de la pandemia.

D) Los trabajadores que perdieron más puestos laborales fueron aquellos que contaban con una educación superior técnica o profesional y su recuperación fue lenta, de lo que podemos concluir que el título académico no necesariamente garantiza la continuidad de un puesto laboral. En cambio, sí se observa una cierta estabilidad en el ingreso mensual de los profesionales con estudios superiores que continuaron siendo empleados entre 2019 y 2021. Por otro lado, hacia 2021, aumentó el empleo informal principalmente en los trabajadores con educación universitaria incompleta o con educación secundaria, es decir, que la pandemia afectó sobre todo a aquellos que se encontraban en el proceso de acentuarse en una profesión. 

En tercer lugar, sobre la hipótesis 3 sobre si la pandemia ha tenido un efecto negativo en el salario sobre todo del trabajador informal, vemos que ciertamente ocurrió un deterioro importante del ingreso promedio mensual reduciéndose en s/.152 entre 2019 y 2021. Ahora bien, esta reducción representó el 5% del ingreso promedio mensual tanto para los trabajadores formales como informales, lo cual se refleja en s/.126 y s/.48 menos respectivamente.

En cuarto lugar, la hipótesis 4 menciona que el deterioro del ingreso ha sido mayor en los grupos más vulnerables como jóvenes y las personas de menor nivel educativo. Sobre este punto, cabe mencionar que principalmente los trabajadores formales de 60 a 64 años vieron sus ingresos comprometidos. De manera similar, los trabajadores formales de 45 a 59 años redujeron sus ingresos. Por el contrario, cabe destacar una ligera recuperación de los ingresos en los trabajadores de 24 años a menos, pero que, sin embargo, permanecen ganando por debajo de la remuneración mínima vital.

A modo de cierre, respecto a la pregunta: ¿cómo la pandemia del COVID-19 ha afectado las condiciones de vida de la Población Económicamente Activa Ocupada (PEAO) urbana, específicamente los cambios en los trabajadores con empleo informal?, podemos concluir que ciertamente la pandemia ha conllevado un deterioro de las condiciones de vida representadas en el ingreso. Sobre todo, se observó que si bien el empleo informal recibió un duro choque durante la pandemia, hacia 2021 mostraba niveles de empleo similares a los prepandemia. Sin embargo, principalmente tanto las mujeres jefas de hogar como los trabajadores entre 60 y 64 años no han logrado reestablecer y/o superar la situación previa a la pandemia.