# Detalles de la investigación {#sec-detalles}

## Tema de Investigación

La pandemia y los trabajadores urbanos con empleo informal en el Perú actual

## Problema de Investigación

El efecto de la pandemia del COVID-19 en las condiciones de vida de los hogares de trabajadores con empleo informal en el Perú urbano

## Pregunta de Investigación

¿Cómo la pandemia del COVID-19 ha afectado las condiciones de vida de la Población Económicamente Activa Ocupada (PEAO) urbana, específicamente los cambios en los trabajadores con empleo informal?

## Preguntas específicas

1.  ¿Cuánto han cambiado los niveles de informalidad del empleo urbano en el país a raíz de la pandemia?

2.  ¿En qué lugares y grupos sociales estos cambios han sido más importantes, considerando principalmente las diferencias por ámbito geográfico, sexo, grupo de edad, nivel educativo y categoría ocupacional?

3.  ¿Cómo estos cambios han afectado los niveles de ingreso de los trabajadores?

## Objetivo de la Investigación

Identificar los cambios experimentados en las condiciones de vida de los hogares de los trabajadores con empleo informal entre el 2019 y 2021

## Objetivos específicos

1.  Detallar las características de la PEA ocupada urbana antes y después de la propagación global del COVID-19

2.  Evaluar la magnitud de los cambios en los niveles de informalidad del empleo entre 2019 y 2021 considerando:

    i.  Dominio geográfico

    ii. Estratos geográficos

    iii. Sexo

    iv. Grupos de edad

    v.  Nivel educativo

    vi. Categoría ocupacional

    vii. Condición de pobreza

3.  Identificar cómo estos cambios han afectado los ingresos de los trabajadores y qué grupos de trabajadores informales se han visto más afectados

## Objeto / Población de estudio

Los hogares de trabajadores con empleo informal en el Perú urbano entre el 2019 y el 2021
