# Introducción {.unnumbered}

La pandemia del COVID-19, la cual arribó al Perú a inicios del 2020, llevó a que muchos países tomen medidas drásticas con el objetivo de contener la propagación del virus. Entre estas medidas, quizás la más importante, fue la restricción, al inicio total y luego parcial, de ciertas actividades económicas en los diferentes rubros del mercado laboral peruano. Este shock ha llevado a que durante el segundo trimestre del 2020 se perdieran 6 millones de empleos en el país [@ipe2020].

La inflexión en el empleo formal fue más crítica en los meses de abril, mayo y junio [@soto2020]; los trabajadores que lograron mantenerse en la formalidad se apoyaron en algunos de los beneficios sociales promulgados por el gobierno para sobrellevar el impacto de la pandemia como la ampliación de cobertura del seguro de vida para el personal de salud en la lucha contra el COVID-19 (DU 037-20202), subsidio por incapacidad temporal a trabajadores diagnosticados por COVID-19 (Resolución N° 563-GG-ESSALUD-2020), financiamiento a afiliados a un sistema de pensiones (DU N° 077-2020), entre otras.

No obstante, los trabajadores informales, dado que no se encuentran protegidos por un contrato laboral ni cuentan con empresas acreedoras a bonos de reactivación, fueron los más afectados por la paralización económica. En el Perú, donde en el 2020 el 68,4% de los trabajadores urbanos eran informales, la desprotección social se volvió la norma antes que la excepción [@inei2021, pp. 119].

La informalidad laboral presenta condiciones variadas entre cada trabajador que dependen en gran medida de su inserción en el mercado laboral. Si bien, se comparte la condición de trabajar sin beneficios sociales reglados por el Estado ni en unidades de producción registradas, el empleo informal puede encontrarse más extendido por la rama de actividad en que se encuentre el trabajador. El @inei2021 detalló que los sectores agricultura, pesca y minería presentan un 95% de empleo informal, permaneciendo como los más afectado por la informalidad desde la década pasada (p.123). Le siguen el rubro de "construcción" y el de "transportes y comunicaciones" con 83%.

Las familias de los trabajadores informales dependen de estos ingresos para su subsistencia y el impacto que ha tenido la pandemia del COVID-19 en estos aún no ha sido completamente determinado, por lo que es incierta la magnitud de este choque; no obstante, este shock nos permite analizar la capacidad de adaptación que tienen los diferentes grupos sociales en función de su modo de vinculación con el mercado laboral y, de esta manera, enfrentar situaciones de repentina crisis.

Es así como esta tesis se propone como pregunta de investigación: ¿cómo la pandemia del COVID-19 ha afectado las condiciones de vida de la Población Económicamente Activa Ocupada (PEAO) urbana, específicamente los cambios en los trabajadores con empleo informal? Asimismo, como preguntas específicas que profundizan la antes mencionada se propone: ¿cuánto han cambiado los niveles de informalidad del empleo urbano en el país a raíz de la pandemia?, ¿en qué lugares y grupos sociales estos cambios han sido más importantes, considerando las diferencias por ámbito geográfico, sexo, grupo de edad, nivel educativo y categoría ocupacional?, ¿cómo estos cambios han afectado los niveles de ingreso de los trabajadores?

Para responder a estas preguntas, realizaremos un análisis longitudinal, evaluando el antes y después de la propagación global del COVID-19 y las condiciones de vida de los hogares cuyos ingresos dependen de miembros que cuentan con un empleo informal.

Para ello, utilizaremos los datos de las Encuestas Nacionales de Hogares (ENAHO) 2019 -- 2021 con énfasis en el módulo 5: Empleo e Ingresos con la finalidad de analizar los cambios en el ingreso de hogares individuales.

La motivación detrás de la presente tesis es observar los cambios y adaptaciones de los trabajadores, en especial los informales, en el contexto de la pandemia. De esta manera, se podrá observar qué grupos sociales se encuentran mayor o menor equipados para situaciones abruptas en el mercado laboral.
